spring:
  application:
    name: lv2-final-mission
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
